from __future__ import annotations

"""
Visualization module for forecast validation results.

Why this file exists:
- Model scripts produce CSV artifacts containing predictions.
- Visualization must remain a separate stage so model results are
  reproducible and plotting does not trigger retraining.
"""

from pathlib import Path
import logging

import pandas as pd
import matplotlib.pyplot as plt


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)
LOGGER = logging.getLogger("forecast_plot")


class PlotError(Exception):
    """
    Raised when plotting fails due to missing files
    or malformed prediction data.
    """


def load_predictions(path: str) -> pd.DataFrame:
    """
    Load prediction artifact generated by validation script.

    Why this exists:
    - Centralized loading ensures the artifact exists and
      has the required columns before plotting.
    """

    csv_path = Path(path)

    if not csv_path.exists():
        raise PlotError(f"Prediction file not found: {csv_path}")

    df = pd.read_csv(csv_path)

    required_columns = {
        "model_name",
        "timestamp_utc",
        "actual_pm2_5",
        "predicted_pm2_5",
    }

    if not required_columns.issubset(df.columns):
        raise PlotError("Prediction file missing required columns")

    df["timestamp_utc"] = pd.to_datetime(df["timestamp_utc"], utc=True)

    return df


def plot_model_predictions(df: pd.DataFrame) -> None:
    """
    Generate forecast comparison plots.

    Why this exists:
    - Visualization reveals model behavior that metrics alone
      cannot show (lagging, overshooting, noise fitting).
    """

    models = df["model_name"].unique()

    fig, axes = plt.subplots(len(models), 1, figsize=(12, 8), sharex=True)

    if len(models) == 1:
        axes = [axes]

    for ax, model in zip(axes, models):

        model_df = df[df["model_name"] == model]

        ax.plot(
            model_df["timestamp_utc"],
            model_df["actual_pm2_5"],
            label="Actual",
        )

        ax.plot(
            model_df["timestamp_utc"],
            model_df["predicted_pm2_5"],
            label=f"{model} Prediction",
        )

        ax.set_title(f"{model} Forecast vs Actual")
        ax.set_ylabel("PM2.5")
        ax.legend()
        ax.grid(True)

    axes[-1].set_xlabel("Timestamp")

    plt.tight_layout()

    output_file = "forecast_validation_plot.png"
    plt.savefig(output_file)

    LOGGER.info("Saved forecast plot to %s", output_file)

    plt.show()


def main() -> None:
    """
    Entry point for visualization workflow.
    """

    try:
        df = load_predictions("forecast_validation_predictions.csv")

        LOGGER.info(
            "Loaded prediction dataset with %d rows",
            len(df),
        )

        plot_model_predictions(df)

    except PlotError as exc:
        LOGGER.exception("Plotting failed: %s", exc)
        raise SystemExit(1)


if __name__ == "__main__":
    main()